package com.voxops.incident;

import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class AiRecommendationService {

    private final IncidentRepository incidentRepository;
    private final TimelineEventRepository timelineEventRepository;
    private final TranscriptSegmentRepository transcriptSegmentRepository;
    private final AiRecommendationRepository aiRecommendationRepository;
    private final RunbookRetrievalService runbookRetrievalService;
    private final AiProviderProperties aiProviderProperties;
    private final Map<AiProviderType, AiRecommendationProvider> providers;
    private final DomainEventPublisher domainEventPublisher;
    private final EventTopicProperties eventTopicProperties;
    private final MeterRegistry meterRegistry;

    public AiRecommendationService(
            IncidentRepository incidentRepository,
            TimelineEventRepository timelineEventRepository,
            TranscriptSegmentRepository transcriptSegmentRepository,
            AiRecommendationRepository aiRecommendationRepository,
            RunbookRetrievalService runbookRetrievalService,
            AiProviderProperties aiProviderProperties,
            List<AiRecommendationProvider> providers,
            DomainEventPublisher domainEventPublisher,
            EventTopicProperties eventTopicProperties,
            MeterRegistry meterRegistry
    ) {
        this.incidentRepository = incidentRepository;
        this.timelineEventRepository = timelineEventRepository;
        this.transcriptSegmentRepository = transcriptSegmentRepository;
        this.aiRecommendationRepository = aiRecommendationRepository;
        this.runbookRetrievalService = runbookRetrievalService;
        this.aiProviderProperties = aiProviderProperties;
        this.providers = new EnumMap<>(AiProviderType.class);
        providers.forEach(provider -> this.providers.put(provider.providerType(), provider));
        this.domainEventPublisher = domainEventPublisher;
        this.eventTopicProperties = eventTopicProperties;
        this.meterRegistry = meterRegistry;
    }

    @Transactional(readOnly = true)
    public List<AiRecommendationResponse> listRecommendations(UUID incidentId) {
        ensureIncidentExists(incidentId);
        return aiRecommendationRepository.findByIncident_IdOrderByCreatedAtDesc(incidentId)
                .stream()
                .map(AiRecommendationResponse::from)
                .toList();
    }

    @Transactional
    public AiRecommendationResponse generateRecommendation(UUID incidentId) {
        Incident incident = incidentRepository.findById(incidentId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Incident not found"));

        List<TimelineEvent> timeline = timelineEventRepository.findByIncident_IdOrderByCreatedAtDesc(incidentId);
        List<TranscriptSegment> transcripts = transcriptSegmentRepository.findByIncident_IdOrderByCreatedAtDesc(incidentId);
        List<RunbookMatch> runbooks = runbookRetrievalService.searchForIncident(incidentId).matches();

        AiRecommendationProvider provider = resolveProvider();
        Timer.Sample sample = Timer.start(meterRegistry);
        AiRecommendationResult result = provider.generate(new AiRecommendationContext(incident, timeline, transcripts, runbooks));
        sample.stop(Timer.builder("voxops_ai_recommendation_generation_seconds")
                .tag("provider", result.provider())
                .register(meterRegistry));

        AiRecommendation recommendation = aiRecommendationRepository.save(
                new AiRecommendation(incident, result.prompt(), result.response(), result.confidence(), result.citations())
        );
        meterRegistry.counter(
                "voxops_ai_recommendations_created_total",
                "provider", result.provider(),
                "status", recommendation.getStatus().name()
        ).increment();

        TimelineEvent timelineEvent = timelineEventRepository.save(new TimelineEvent(
                incident,
                TimelineEventType.NOTE,
                "AI recommendation generated by %s from current timeline and transcript context."
                        .formatted(result.provider()),
                "ai-recommendation-service"
        ));

        publishRecommendationEvent(recommendation, result);
        publishTimelineEvent(timelineEvent);

        return AiRecommendationResponse.from(recommendation);
    }

    private void publishRecommendationEvent(AiRecommendation recommendation, AiRecommendationResult result) {
        domainEventPublisher.publish(
                eventTopicProperties.activeTopics().recommendationCreatedTopic(),
                recommendation.getIncidentId().toString(),
                DomainEvent.of(
                        "ai.recommendation.created",
                        recommendation.getIncidentId(),
                        "incident",
                        Map.of(
                                "recommendationId", recommendation.getId().toString(),
                                "provider", result.provider(),
                                "status", recommendation.getStatus().name(),
                                "confidence", recommendation.getConfidence(),
                                "citations", recommendation.getCitations(),
                                "createdAt", recommendation.getCreatedAt().toString()
                        )
                )
        );
    }

    private void publishTimelineEvent(TimelineEvent event) {
        domainEventPublisher.publish(
                eventTopicProperties.activeTopics().timelineCreatedTopic(),
                event.getIncidentId().toString(),
                DomainEvent.of(
                        "timeline.event.created",
                        event.getIncidentId(),
                        "incident",
                        Map.of(
                                "timelineEventId", event.getId().toString(),
                                "eventType", event.getEventType().name(),
                                "summary", event.getSummary(),
                                "source", event.getSource(),
                                "createdAt", event.getCreatedAt().toString()
                        )
                )
        );
    }

    private AiRecommendationProvider resolveProvider() {
        AiProviderType providerType = aiProviderProperties.activeProvider();
        AiRecommendationProvider provider = providers.get(providerType);
        if (provider == null) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "AI provider not registered: " + providerType);
        }
        return provider;
    }

    private void ensureIncidentExists(UUID incidentId) {
        if (!incidentRepository.existsById(incidentId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Incident not found");
        }
    }

}
