FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn -pl services/incident-service -am package -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/services/incident-service/target/incident-service-0.1.0-SNAPSHOT.jar app.jar
EXPOSE 8081
CMD ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
